version: 2
updates:
  # Go modules updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      kubernetes:
        patterns:
          - "k8s.io*"
          - "sigs.k8s.io/*"  # Added to catch all k8s-related packages
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
      - "integration-test"  # Added to trigger integration tests

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      actions:
        patterns:
          - "actions/*"
          - "github/*"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"

  # Docker image updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    groups:
      golang-docker:
        patterns:
          - "golang*"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "automerge"
      - "integration-test"  # Added to trigger integration tests
