linters:
  enable:
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unused

run:
  timeout: 5m
  tests: true
  go: "1.23"

linters-settings:
  goimports:
    local-prefixes: github.com/jjshanks/pod-label-webhook
  govet:
    enable:
      - shadow
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
      - name: context-as-argument
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
      - name: receiver-naming
        severity: warning
        disabled: false
      - name: error-return
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: error-strings
        severity: warning
        disabled: false
      - name: if-return
        severity: warning
        disabled: false
      - name: increment-decrement
        severity: warning
        disabled: false
      - name: var-declaration
        severity: warning
        disabled: false
      - name: range
        severity: warning
        disabled: false
      - name: unexported-return
        severity: warning
        disabled: false
      - name: errorf
        severity: warning
        disabled: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
