# manifests/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-label-webhook
  namespace: pod-label-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-label-webhook
  template:
    metadata:
      labels:
        app: pod-label-webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/jjshanks/pod-label-webhook:$(VERSION)
          imagePullPolicy: IfNotPresent
          args:
            - "--cert-file=/tls/tls.crt"
            - "--key-file=/tls/tls.key"
          env:
            - name: WEBHOOK_LOG_LEVEL
              value: "info"
            - name: WEBHOOK_CERT_FILE
              value: "/tls/tls.crt"
            - name: WEBHOOK_KEY_FILE
              value: "/tls/tls.key"
          ports:
            - containerPort: 8443
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          volumeMounts:
            - name: cert
              mountPath: /tls
              readOnly: true
      volumes:
        - name: cert
          secret:
            secretName: pod-label-webhook-cert
            defaultMode: 0600
---
apiVersion: v1
kind: Service
metadata:
  name: pod-label-webhook
  namespace: pod-label-system
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: pod-label-webhook
