name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.2.3)'
        required: true
        type: string
      prerelease:
        description: 'Is this a prerelease?'
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  packages: write

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check version format
        run: |
          if ! echo "${{ github.event.inputs.version }}" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: Version must be in format X.Y.Z"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create and push tag
        run: |
          TAG="v${{ github.event.inputs.version }}"
          echo "Creating tag $TAG"
          git tag $TAG
          echo "Pushing tag to origin"
          git push origin $TAG || {
            echo "Failed to push tag"
            exit 1
          }
          echo "Successfully pushed tag $TAG"
          
      - name: Verify tag exists
        run: |
          TAG="v${{ github.event.inputs.version }}"
          if git ls-remote --tags origin | grep -q "$TAG"; then
            echo "Tag $TAG successfully created on remote"
          else
            echo "Tag $TAG not found on remote"
            exit 1
          fi

      - name: Trigger release workflow
        run: |
          echo "Release workflow should be triggered by tag push"
          echo "Tag: v${{ github.event.inputs.version }}"
          echo "Please check the Actions tab for the release workflow"